   ServerName www.acms.cweb.com.au
   ServerAlias acms.cweb.com.au 
   ProxyTimeout 300
   Timeout 300
   DocumentRoot /home/www/acms.cweb.com.au/pages
   DirectoryIndex index.html
   SetEnv TZ Australia/Sydney
   ErrorLog /home/www/acms.cweb.com.au/var/log/www_error_log
   CustomLog /home/www/acms.cweb.com.au/var/log/www_access_log combined
   #php_flag magic_quotes_gpc off
   #php_value include_path "/home/www/acms.cweb.com.au/lib:/usr/local/lib/php:."
   #php_value auto_prepend_file "header.php"

   Alias /webrobot.php /home/www/acms.cweb.com.au/webrobot/webrobot.php
   Alias /js/editor.js /home/www/acms.cweb.com.au/webrobot/js/editor.js

<Directory /home/www/acms.cweb.com.au/pages>
    # Allow .htaccess files to override other settings.
    AllowOverride All
    Options +Includes
    AddOutputFilter INCLUDES .html
</Directory>

<Directory /home/www/acms.cweb.com.au/webrobot>
    # Password protect only the PHP files in the AI editor directory.
    <FilesMatch "\.php$">
        AuthType Basic
        AuthName "AI Editor - Restricted Area"
        AuthUserFile /home/ec2-user/etc/htpasswd
        Require valid-user
    </FilesMatch>
</Directory>

<Directory /home/www/acms.cweb.com.au/pages/upload>
    # Disable directory browsing for security.
    Options -Indexes

    # Prevent execution of any scripts.
    <Files "*">
      SetHandler default-handler
    </Files>
</Directory>
